### ISSUE TITLE
More information needed

### ISSUE THREAD

**Issue by farhang1** [markchen8717/Gekko_Bot_Trading_Strategies#3]
Hi,
Thanks for the great work. I think you did a smart job to combine the two most important indicators and neural net. Would you please explain how to use the files? I mean for a beginner level. 
And also, if you could test your work, how is it?
Thanks

**Comment by markchen8717** [comment]
Thank you very much for the compliment! Please refer to the project README file for instructions on how to test out the strategies. For additional detail, please check out the comments inside the each strategy.js files.
