### ISSUE TITLE
./DQL_OUT/DQL_out.json is missing

### ISSUE THREAD

**Issue by domgolonka** [markchen8717/Gekko_Bot_Trading_Strategies#5]
Can you provide this file? I tried creating an empty Json file, but it still gives me an error: { Error: No input or output size given

**Comment by vidukapoor** [comment]
hi @domgolonka did u got the solution for this issue, for LSTM strategy its written what to comment and for the first time.

**Comment by Escaliert** [comment]
same error

**Comment by Cazs03** [comment]
We need to have a model pre-trained? how can get this? @markchen8717

**Comment by markchen8717** [comment]
A pre-trained model is not required. One can comment out the import nn portion of the code and have the strategy generate a new model json file.
